/**
 * @author Deloitte
 * @date 07/20/2024
 * @description Wrapper Class to store Account (Business) details for Onboarding Inputs
 * data creation process.
 **/
@SuppressWarnings('PMD.ExcessivePublicCount, PMD.TooManyFields, PMD.FieldNamingConventions')
public class BusinessAccountWrapper {
    public String brand;
    public String legalBusinessName;
    public String billingStreet;
    public String billingCity;
    public String billingStateCode;
    public String billingCountryCode;
    public String billingPostalCode;
    public String taxId;
    public String provisionalTax;
    public String Name;
    public String photoShootName;
    public String photoShootLastName;
    public String photoShootEmail;
    public String photoShootPhone;
    public String photoShootMobile;
    public String businessName;
    public String businessLastName;
    public Date businessOwnerDOB;
    public String businessOwnerCountry;
    public String businessOwnerStreet;
    public String businessOwnerCity;
    public String businessOwnerState;
    public String businessOwnerZip;
    public String businessEmail;
    public String businessPhone;
    public String businessDirectorName;
    public String businessDirectorLastName;
    public String businessDirectorEmail;
    public String businessDirectorPhone;

    public String billingContactEmail;
    public Date representativeDateOfBirth;
    public String representativeEmail;
    public String representativeFirstName;
    public String representativeLastName;
    public String representativePhone;
    public String bankAccountNumber;
    public String routingNumber;
    public String institutionNumber;
    public String paymentDescriptor;

    public String addressLine1;
    public String street;
    public String city;
    public String state;
    public String zipPostalCode;
    public String country;

    public String paymentStreet;
    public String paymentCity;
    public String paymentStateCode;
    public String paymentZipPostalCode;
    public String paymentCountryCode;
    public String paymentCountry;

    public String billingContactFirstName;
    public String billingContactLastName;
    public String billingContactPhone;
}